### ISSUE TITLE
aws-vault: command not found

### ISSUE THREAD

**Issue by kangaechu** [sawadashota/raycast-extension-aws-vault#1]
Thank you creating this nice extension!

I have an error  while running this extension.
How do you set PATH to Raycast?

```shell
2022-02-04 21:09:32.230 F  Raycast[52511:9b884] [com.raycast.extensions.aws-vault:index] error: Command failed: aws-vault list
/bin/sh: aws-vault: command not found
```

## Environment:

- Mac: MacBook Air (M1, 2020)
- OS: macOS Monterey 12.2
- path to aws-vault: /opt/homebrew/bin/aws-vault

**Comment by sawadashota** [comment]
Thanks for reporting. Resoveld by #2

**Comment by kangaechu** [comment]
Thank you!
